name: Build and Deploy to AKS with ACR (Fixed for amd64)

on:
  push:
    branches:
      - main

env:
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}
  BACKEND_IMAGE: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/java-backend
  FRONTEND_IMAGE: ${{ secrets.AZURE_ACR_LOGIN_SERVER }}/java-frontend

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build backend JAR
        run: |
          cd backend
          ./mvnw clean package -DskipTests || mvn clean package -DskipTests

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker Login to ACR
        run: |
          az acr login --name ${{ secrets.AZURE_ACR_NAME }}

      - name: Build & Push Backend Docker Image (linux/amd64)
        run: |
          docker buildx build --platform linux/amd64 -t $BACKEND_IMAGE:latest ./backend --push

      - name: Build & Push Frontend Docker Image (linux/amd64)
        run: |
          docker buildx build --platform linux/amd64 -t $FRONTEND_IMAGE:latest ./frontend --push

      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing

      - name: Deploy to AKS
        run: |
          sed -i "s|your-backend-image|$BACKEND_IMAGE:latest|g" k8s/backend-deployment.yaml
          sed -i "s|your-frontend-image|$FRONTEND_IMAGE:latest|g" k8s/frontend-deployment.yaml
          kubectl apply -f k8s/ --validate=false
